### ISSUE TITLE
excludeTransform method doesn't work on Windows

### ISSUE THREAD

**Issue by holubec-petr** [nebula-plugins/gradle-jakartaee-migration-plugin#3]
**Steps to Reproduce**
* Use JakartaEE migration plugin in project
* Define some exclusions i.e. `excludeTransform(<something>)`
* Build project on Windows

**Actual Results**
The plugin does not exclude anything

**Expected Results**
Defined artifacts will be excluded from transformation

**Additional Info**
Problem is in `JakartaEeMigrationTransform` class because `excludedPaths` variable uses system specific file separators.

I will try to provide PR today.

**Comment by DanielThomas** [comment]
Released https://github.com/nebula-plugins/gradle-jakartaee-migration-plugin/releases/tag/v0.4.0
