### ISSUE TITLE
[Enhancement] Possibility to include artifact for transformation

### ISSUE THREAD

**Issue by holubec-petr** [nebula-plugins/gradle-jakartaee-migration-plugin#5]
When it comes to transformation, the plugin transforms all artifacts and user is able to exclude some artifacts with specific group and name.

It think it would be more explicit and better for future maintenance to have possibility to include just artifacts that the user wants to transform. It will be completely clear when a new version of the dependency would be implemented (and using Jakarta API) that the transformation of the artifact is not needed anymore.

Thank you for consideration and a PR is coming.

**Comment by DanielThomas** [comment]
Sounds good. Comments on the PR.

**Comment by DanielThomas** [comment]
Available in 0.5.0.
